blank_issues_enabled: false
contact_links:
    - name: ğŸ™‹ğŸ¼â€â™‚ï¸ Support Questions & Other
      url: https://github.com/PHP-Open-Source-Saver/jwt-auth/discussions/new
      about: 'I need assistance or clarification on usage of this library.'
