name: Tests / PHPUnit

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - release/**

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]
        laravel: [6.*, 7.*, 8.*, 9.*]
        stability: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        coverage: [none]
        exclude:
          - laravel: 9.*
            php: 7.4
        include:
          - laravel: 6.*
            dotenv: ^3.3

          - laravel: 7.*
            dotenv: ^4.0

          - laravel: 8.*
            dotenv: ^5.2

          - laravel: 9.*
            dotenv: ^5.2

          - php: 8.0
            laravel: 9.*
            stability: prefer-stable
            os: ubuntu-latest
            coverage: xdebug
            dotenv: ^5.2

    name: '[PHP ${{ matrix.php }}] [Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}] [${{ matrix.coverage }} coverage]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring json openssl
          coverage: ${{ matrix.coverage }}
          ini-values: memory_limit=-1

      - name: Setup Problem Matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set Minimum PHP 8.0 Versions
        run: composer require phpunit/phpunit:^9.4 --no-interaction --no-progress --no-update
        if: matrix.php >= 8

      - name: Set Minimum Laravel ${{ matrix.laravel }} Versions
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-progress --no-update
          composer require "vlucas/phpdotenv:${{ matrix.dotenv }}" --no-interaction --no-progress --no-update --dev

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}
            composer-${{ runner.os }}-${{ matrix.php }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        run: composer update --no-progress --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: composer test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: matrix.coverage == 'xdebug'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          yml: ./codecov.yml
